inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

LineLength:
  Max: 140

AllCops:
  Exclude:
  - 'bin/*'
  - 'config/**/*'
  - 'db/**/*'
  - 'lib/tasks/_force_reload.rake'
  - 'spec/spec_helper.rb'
  - 'vendor/bundle/**/*'